spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: "CHANGE-THIS-TO-A-VERY-LONG-RANDOM-SECRET-KEY-AT-LEAST-64-BYTES"
  access-exp-min: 60     # 60ë¶„
  header: Authorization
  prefix: "Bearer "
logging:
  level:
    org.hibernate.SQL: debug
