spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringSecurity?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${SECRET_KEY}
  access-expiration: 10
  refresh-expiration: 604800
  header: Authorization
  prefix: "Bearer "
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_POST}
logging:
  level:
    org.hibernate.SQL: debug
