spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${SECRET_KEY}
  access-expiration: 20
  refresh-expiration: 604800
  header: Authorization
  prefix: "Bearer "
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_POST}
logging:
  level:
    org.hibernate.SQL: debug
