spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringSecurity?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${SECRET_KEY}
  access-exp-min: 60     # 60ë¶„
  header: Authorization
  prefix: "Bearer"
redis:
  host: 127.0.0.1
  port: 6379
logging:
  level:
    org.hibernate.SQL: debug
